// Common disposable/temporary email domains, blocked at signup. Not an
// exhaustive list (new disposable services appear constantly — this is a
// defense-in-depth speed bump, not a guarantee), but covers the large
// majority of widely-used throwaway-inbox providers.
const DISPOSABLE_EMAIL_DOMAINS = new Set([
  "mailinator.com",
  "guerrillamail.com",
  "guerrillamail.info",
  "guerrillamail.biz",
  "guerrillamail.de",
  "guerrillamail.org",
  "guerrillamail.net",
  "sharklasers.com",
  "10minutemail.com",
  "10minutemail.net",
  "20minutemail.com",
  "temp-mail.org",
  "tempmail.com",
  "tempmail.net",
  "tempmailo.com",
  "throwawaymail.com",
  "yopmail.com",
  "yopmail.net",
  "yopmail.fr",
  "trashmail.com",
  "trashmail.net",
  "getnada.com",
  "mailnesia.com",
  "mailcatch.com",
  "mintemail.com",
  "moakt.com",
  "dispostable.com",
  "fakeinbox.com",
  "maildrop.cc",
  "mohmal.com",
  "emailondeck.com",
  "spamgourmet.com",
  "mytemp.email",
  "tempinbox.com",
  "tempr.email",
  "discard.email",
  "discardmail.com",
  "mailnull.com",
  "spam4.me",
  "byom.de",
  "einrot.com",
  "fleckens.hu",
  "guerrillamailblock.com",
  "harakirimail.com",
  "jetable.org",
  "nada.email",
  "spambog.com",
  "spamfree24.org",
  "tempmail.de",
  "tempmail.plus",
  "burnermail.io",
  "inboxkitten.com",
  "luxusmail.org",
  "mailtemp.info",
  "emailfake.com",
  "fakemailgenerator.com",
  "crazymailing.com",
  "tempail.com",
  "airmail.cc",
  "anonbox.net",
  "correotemporal.org",
  "correotemporal.com",
  "onewaymail.com",
  "meltmail.com",
  "instantemailaddress.com",
]);

export function isDisposableEmail(email: string): boolean {
  const domain = email.trim().toLowerCase().split("@")[1];
  if (!domain) return false;
  return DISPOSABLE_EMAIL_DOMAINS.has(domain);
}
